### PR TITLE
👋 Add Hello API

### PR DESCRIPTION
**Pull request by TorzuoliH**
- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by navanchauhan** [comment]
I think it's a positive PR

**Comment by davemachado** [comment]
Hi @TorzuoliH , thanks for the PR. Can you please change the Title to `HelloSalut`, as we try to refrain from having punctuation in the title. Thanks!

**Comment by TorzuoliH** [comment]
Hi @davemachado, this is done 😄 Thanks for details!

**Comment by davemachado** [comment]
Almost 😉 - you just need to remove the `!` at the end.

**Comment by TorzuoliH** [comment]
@davemachado Ok I think I'm good right now haha

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
