### PR TITLE
Added a few LabStack APIs

### PR DESCRIPTION
**Pull request by vishr**
Signed-off-by: Vishal Rana <vr@labstack.com>

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @vishr , thanks for the PR. Can you please put the auth type values in backticks (\`)? It appears our validator does not check for this, so I will make the changes to test against that in the future.

**Comment by davemachado** [comment]
maintainer note: fixed the backtick build check issue in 21901ee2ac0884292cdc0cfb82d333409745dd6a

**Comment by vishr** [comment]
@davemachado Just did it, thanks.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
