### PR TITLE
Adds section 'Travel' and APIs.is (Collection of Icelandic APIs)

### PR DESCRIPTION
**Pull request by zebroc**
Adds section 'Travel' and APIs.is (Collection of Icelandic APIs)

I think it makes sense to add a 'Travel' section, there surely are other APIs out there that fit in it

### CODE REVIEW

**Comment by jbrooksuk** [comment]
We've put a few Travel related API's under Transportation. I wonder if we should rename it to Travel/Transportation or do as you've done here and separate them?

Ping @davemachado @mikestreety

**Comment by mikestreety** [comment]
Travel is transportation?! 😉 I'd be in favour of either:

- Separating but calling it Public Transport
- Keeping them together with a slash

**Comment by davemachado** [comment]
I could have sworn I added more to address this idea to my response in #418 .... guess not!

IMO, I would recommend `Travel & Transportation` for now - if we start receiving an influx of PRs for that section and there is enough meat for both `Travel` AND `Transportation`, then and only then would splitting make sense (this idea would still hold for any section, such as if we ended up with enough `Food` entries AND `Drink` entries to warrant splitting `Food & Drink`). Like I mentioned in the linked PR, I would hate to see a whole bunch of mini-sections start popping up.

**Comment by mikestreety** [comment]
Yup, I'm with @davemachado.

@zebroc, would you mind popping this addition into Transportation?

**Comment by zebroc** [comment]
Done.

**Comment by jbrooksuk** [comment]
Perfect! Thanks :)

**Pull request merged**
