### PR TITLE
add YouTube API

### PR DESCRIPTION
**Pull request by marcobiedermann**

### CODE REVIEW

**Comment by toddmotto** [comment]
Can we add this under social if possible? Or media, what do you think? I'm swayed towards Social :)

**Comment by marcobiedermann** [comment]
I suggest splitting it up:
* Blogs (e.g. Medium)
* Books (e.g. Good Reads)
* Images (e.g. Unsplash, Flickr, Imgur, dribbble)
* Media (e.g. Chuck Norris Database, Rijksmuseum)
* Music (e.g. Soundcloud, iTunes, TheMovieDB)
* Social (e.g. Facebook, Twitter, G+)
* Video (e.g. YouTube, Vimeo)

**Comment by toddmotto** [comment]
I will attempt this at some stage, there are too many PRs and changes at the moment - ahhh!

**Comment by marcobiedermann** [comment]
@toddmotto Yeah, no problem. I opened up an issue to keep track of it.
See #127

**Pull request merged**
