### PR TITLE
Add OpenStreetMap API

### PR DESCRIPTION
**Pull request by yunque**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you squash into one commit, please.

**Comment by toddmotto** [comment]
Squash and merge button @jbrooksuk ! ;)

**Comment by jbrooksuk** [comment]
> Squash and merge button @jbrooksuk ! ;)

I always forget about that new button!

**Comment by yunque** [comment]
Wasn't aware of the squash & merge function. Will look out for it next time!

**Pull request merged**
