### PR TITLE
Add FEC API to list

### PR DESCRIPTION
**Pull request by chief10**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
        
- [x] Your additions are ordered alphabetically.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [ ] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @chief10 , can you please fix the errors found in the build? Thanks.

**Comment by chief10** [comment]
Got it! Sorry about that!

**Comment by davemachado** [comment]
Thanks, can you please also alphabetize the section?

**Comment by chief10** [comment]
For sure.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
