### PR TITLE
add Transitland API

### LINKED ISSUE #69: Add Transit Land
Please consider adding the newly-released Transitland API from here: https://transit.land/.

Thanks!

### PR DESCRIPTION
**Pull request by ZakariaRidouh**
this PR fixes #69

### CODE REVIEW

**Comment by toddmotto** [comment]
This looks like a global API rather than just bay area?

**Comment by drewda** [comment]
Thanks for noticing, @toddmotto. Transitland has been expanding to cover other parts of the world, listed at https://transit.land/feed-registry/

**Comment by jbrooksuk** [comment]
Done!

**Comment by drewda** [comment]
👍 thanks, @jbrooksuk!

**Pull request closed without merging**
