### PR TITLE
Add RoutingNumbers.info

### PR DESCRIPTION
**Pull request by ecwyne**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [X] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [X] Your additions are ordered alphabetically.
- [X] Your submission has a useful description.
- [X] Each table column should be padded with one space on either side.
- [X] You have searched the repository for any relevant issues or PRs.
- [X] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by ecwyne** [comment]
@davemachado I'm happy to rebase this PR if #500 is required first to fix the build

**Comment by davemachado** [comment]
Hi @ecwyne , thanks for the (2) PR's 😉 

No worries about rebasing, I already merged in #500 so as long as you can remove "API ..." from the `Description`, we'll be good to go! (everything here is an API, so no need to specify)

**Comment by ecwyne** [comment]
Thanks @davemachado 

Should be good to go now!

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
