### PR TITLE
Add Openwhyd's public API to the "Music" section

### PR DESCRIPTION
**Pull request by adrienjoly**
Hi again! This PR is an alternative to #832.

Openwhyd is a free and open-source music curation service that allows users to create playlists of music tracks from various streaming platforms (YouTube, SoundCloud, Vimeo, Deezer...) and to discover the music from other users.

Besides our Cookie-based API (as described in PR #832), we give free access to our users' public profiles and playlists in JSON format.

As an example of use of that API, I wrote a script to download the music tracks mentioned in the JSON response of my own playlists: [openwhyd-pl-dl](https://github.com/adrienjoly/openwhyd-pl-dl)

I'm happy to help if you have any questions and/or suggested changes.

Thanks again for your work, and for your consideration! ^^

---

PR check-list:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- ~~[ ] Any category you are creating has the minimum requirement of 3 items~~ (N/A)
- [x] All changes have been [squashed][squash-link] into a single commit

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @adrienjoly , thanks for the PR. Any chance you can link to a shorter URL? Perhaps you could have `openwhyd.org/faq` point to the longer github link?

**Comment by adrienjoly** [comment]
Hi Dave!

As you suggested, I shortened the URL of Openwhyd's API documentation to: https://openwhyd.org/api :-)

I took that opportunity to include the (auth-free) Data Export API into our main API documentation file.

**Comment by adrienjoly** [comment]
Unfortunately, Travis seems to see a `404` for that URL, even though the following `curl` command says that it should be a `307` (temporary redirect):

```sh
$ curl -v https://openwhyd.org/api 2>&1 | grep "< HTTP"
< HTTP/1.1 307 Temporary Redirect
```

Is there anything I can do to help? (Unfortunately I was not able to restart the CI myself)

**Comment by adrienjoly** [comment]
If that can help, I activated GitHub pages in order to also be able to reach the documentation file from that direct URL: https://openwhyd.github.io/openwhyd/API. I will update my PR, to see if solves the issue.

**Comment by davemachado** [comment]
Looks great, thanks @adrienjoly !

**Comment by adrienjoly** [comment]
Awesome, thank you Dave! :-)

Have a good one!

**Pull request merged**
