### PR TITLE
Add OpenWeatherMap API

### PR DESCRIPTION
**Pull request by laco0416**
OpenWeatherMap is a very useful weather data service!

### CODE REVIEW

**Comment by toddmotto** [comment]
Hey @laco0416 ! The readme has had a slight restructure, could you update your PR if poss please so I can merge :)

**Comment by laco0416** [comment]
@toddmotto yep! I fixed it :+1:

**Comment by toddmotto** [comment]
Legendary, thanks!

**Comment by laco0416** [comment]
Thanks a lot!

**Pull request merged**
