### PR TITLE
Cryptocurrency mining service mineralt.io

### PR DESCRIPTION
**Pull request by itelmenko**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ X ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ X ] Your additions are ordered alphabetically
- [ X ] Your submission has a useful description
- [ X ] The description does not end with punctuation
- [ X ] Each table column should be padded with one space on either side
- [ X ] You have searched the repository for any relevant issues or pull requests
- [ X ] Any category you are creating has the minimum requirement of 3 items
- [ X ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @itelmenko , thanks for the PR. Unfortunately, this service does not fit the criteria for this repository.

**Comment by itelmenko** [comment]
@davemachado What criteria do you mean? Could you explain, please?

**Comment by davemachado** [comment]
This library is a reference for free services that offer data that users can download and access to build web applications. This service's API is not a data API, but rather a management API.

**Comment by itelmenko** [comment]
Thank you! Could you remove this thread, please?

**Comment by davemachado** [comment]
I'm not sure what you mean by "remove this thread". Pull Requests are closed, not deleted.

**Comment by itelmenko** [comment]
Could you delete this conversation and this pull request, please? :)

**Comment by davemachado** [comment]
Pull requests are not deleted so that others in the future can see if something they'd like to contribute has been discussed before.

**Pull request closed without merging**
