### PR TITLE
Added NewsAPI to the Media Section

### PR DESCRIPTION
**Pull request by norrisollie**

### CODE REVIEW

**Comment by mikestreety** [comment]
Hi @norrisollie - thanks for this 😄 . 

Would you mind putting it in alphabetical order please? By my reckoning it would go just above `OMDB`.

Thanks!

**Comment by davemachado** [comment]
Also, @norrisollie , the Media section has been dissolved into other sections (see PR #231). Therefore, this should be moved into a new section so we don't end starting another Media section.

**Comment by mikestreety** [comment]
Ah, good spot @davemachado!

**Comment by mikestreety** [comment]
This could now be moved to the new "News" section, created in #238

**Comment by mikestreety** [comment]
Closing this due to no response

**Pull request closed without merging**
