### PR TITLE
Adds ProxyCrawl

### PR DESCRIPTION
**Pull request by proxycrawl**
Adds ProxyCrawl and we made sure about the following 👍 

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

Thanks

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @proxycrawl , thanks for the PR. It appears that there's no free tier, as I use the price calculator for 1 page and it starts cost money.

**Comment by proxycrawl** [comment]
@davemachado the pricing calculator shows the prices of the tiers, that would be the monthly price regardless of the free 1000 API requests. The free tier is enabled by default to any new account and the API is open directly to 1000 free requests. Does that help?

**Comment by proxycrawl** [comment]
@davemachado no, there is no charge if you only use the 1000 free API requests. You don't even have to add your card details to use them.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
