### PR TITLE
Make API names links, remove Go! column

### PR DESCRIPTION
**Pull request by jezmck**
as per issue #727

### CODE REVIEW

**Comment by jezmck** [comment]
I don't know what the fail is, but the diff previews also failed, possibly because it's so long.

**Comment by mikestreety** [comment]
Thanks for doing this :)

It fails as the checks are expecting a "Go" link 👍 

Need @davemachado to jump in and update his script!

**Comment by davemachado** [comment]
Hi guys, sorry for the delay here. I'll cook up a PR for the build scripts changes. 

This formatting change would also require a few changes to this project's API as well. I'll prep a PR for those needed changes and once that's ready we can merge everything :)

**Comment by davemachado** [comment]
I have two PRs ready to go: 

- Build script changes: https://github.com/toddmotto/public-apis/pull/741
- API changes: https://github.com/davemachado/public-api/pull/6

@jezmck once you resolve the merge conflicts in the README (which basically just means re-running your regex find-and-replace again on the new upstream changes) and this PR is ready to merge, I can take care of merging all three changes and ensure nothing breaks along the way.

**Comment by jezmck** [comment]
I resolved the conflict manually in the editor here, rather than rerunning the regex since it didn't seem complex enough to need it. There is therefore a chance that I've missed something.

**Comment by davemachado** [comment]
Hi @jezmck , can you please share the regex you're running? Thanks.

**Comment by jezmck** [comment]
Sorry, I no longer have the regex I used, but I've rewritten it;
`^\| (.*?) \| (.*) \| \[Go!\]\((.*)\) \|$`, with this replacement: `| [$1]($3) | $2 |`

**Comment by davemachado** [comment]
Hey guys, in order to help @jezmck not have to deal with painful merge conflict resolutions on this PR, I used [this gist](https://gist.github.com/davemachado/fb3b20642f807543730ec5505996760c) to move the links and this is merged in at e2b66cea263d77107000855ce66fb3554922dd02 . Thanks @jezmck for the great idea! 😄

**Pull request closed without merging**
