### PR TITLE
added https://robohash.org/

### PR DESCRIPTION
**Pull request by brakmic**
Robohash generates unique avatar images.

### CODE REVIEW

**Comment by toddmotto** [comment]
Hey man, could you merge, getting conflicts right now.

**Comment by brakmic** [comment]
That's weird, sorry. 

I think it's best to delete this PR and make a new one using the current version of README.

Ok?

**Comment by toddmotto** [comment]
Totally your call, I can add it manually if you like, just don't know if you wanted the contrib :)

**Comment by brakmic** [comment]
No problem. The contrib is not that important.

**Pull request closed without merging**
