### PR TITLE
Add letsvalidate api

### PR DESCRIPTION
**Pull request by hbakhtiyor**

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @hbakhtiyor , thanks for the pull request. I see you added this link to both the `Animals` section and a new `Misc` section. We are not looking to create a `Misc` section anytime soon, since those sort of things lead to a lot of future uncategorized entries that could fall under a `Misc` category. I would suggest moving this to the `development` section. Also, could you please remove the reference under the `Animals` section? Thanks.

**Comment by hbakhtiyor** [comment]
Hi @davemachado,  the reference under not `Animals` section, but under `Photography`

**Comment by davemachado** [comment]
Can you please put the entry in alphabetical order? Thanks.

**Comment by hbakhtiyor** [comment]
done

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
