### PR TITLE
Added video download api

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by YannBertrand** [comment]
Is this legal 😁?

**Comment by jbrooksuk** [comment]
I'm tempted not to add this one. Best to leave @toddmotto to decide.

**Comment by wesbos** [comment]
It totally depends what you use it for. A lot of my youtube videos can be downloaded legally. I say we add it!

**Comment by YannBertrand** [comment]
I'd love it too :pray:

**Comment by jbrooksuk** [comment]
Merged :)

**Pull request merged**
