### PR TITLE
Hummingbird is dead, Long live Kitsu

### PR DESCRIPTION
**Pull request by Epictek**
Removed Hummingbird and updated with the Kitsu api details.

Source: https://medium.com/heykitsu/hummingbird-is-dead-long-live-kitsu-bda6ccfbbcce#.xixj9r30c
https://forums.hummingbird.me/t/kitsu-api-documentation/33367

### CODE REVIEW

**Comment by davemachado** [comment]
[Another source](https://forums.hummingbird.me/t/goodbye-hummingbird-hello-kitsu/33238) confirms Hummingbird is down and Kitsu, still unpaid, is taking its place.

Thanks @Epictek !

**Comment by davemachado** [comment]
@Epictek it looks like the new API [uses OAuth for authentication](http://docs.kitsu17.apiary.io/#introduction/authentication).Can you please update the listing as needed?

**Comment by Epictek** [comment]
Sorry the contribution guide seems kind of misleading as it said to put No if authentication is not required to use whereas the API can work without authentication (read-only)

**Comment by davemachado** [comment]
valid point, @Epictek . In the case of this API, however, we'll want to cover what type of authentication is used when required. Thanks again for keeping us updated!

**Pull request merged**
