### PR TITLE
Added: Battuta (Geolocation)

### PR DESCRIPTION
**Pull request by MedUnes**
Added; Battuta: A (country/region/city) in-cascade location API

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by mikestreety** [comment]
Hey @MedUnes 

Thanks for the PR, mind wrapping apiKey in backticks (`) please?

**Comment by MedUnes** [comment]
fixed!

**Comment by MedUnes** [comment]
also fixed/respected the alphabetic order

**Comment by davemachado** [comment]
Thanks @MedUnes !

**Pull request merged**
