### PR TITLE
Added Unplugg Automated Forecasting API

### PR DESCRIPTION
**Pull request by ruimagalhaes**
Added under Machine Learning

### CODE REVIEW

**Comment by jbrooksuk** [comment]
The build is not failing because of your link. Don't worry!

**Comment by davemachado** [comment]
@ruimagalhaes does this API support HTTPS? All the examples in the docs seem to use HTTP.

**Comment by ruimagalhaes** [comment]
@davemachado yes, the API does support https. We are on the process to bring it to the site too but the API is definitely covered. Cheers!

**Comment by davemachado** [comment]
@ruimagalhaes thanks, looks like the endpoint is ` https://api.unplu.gg/`, so looks good to me!

**Pull request merged**
