### PR TITLE
Stormglass

### PR DESCRIPTION
**Pull request by pellepersson**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items

### CODE REVIEW

**Comment by pellepersson** [comment]
Hello @davemachado! There is a free tier for developers. The stormglass.io page was just not updated when I made the pull request. Sorry for that!

**Comment by Robinson133** [comment]
First

**Comment by davemachado** [comment]
Hey @pellepersson , not sure if you're a developer for StormGlass or not, but I'm hoping you can provide some type of documentation that shows that there is a free tier. Maybe there is something extra that you can see while logged in?

**Comment by pellepersson** [comment]
@davemachado - Of course! The information is now added as well as support for HTTPS. Thanks!

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
