### PR TITLE
Added Jikan API

### PR DESCRIPTION
**Pull request by irfan-dahir**

### CODE REVIEW

**Comment by GeorgeWL** [comment]
is this really needed when thhe official already exists?

**Comment by davemachado** [comment]
@GeorgeWL can you please clarify your comment?

**Comment by irfan-dahir** [comment]
@GeorgeWL 
The official one lacks pretty much everything this one provides. 

Such as getting anime, manga, character & person data. Including extended features such as anime/manga episodes & characters/staff. 

And other upcoming features such as a paginated search option, forum posts, etc, etc.

This is not the official API. This is an Unofficial one that simply extends the official one.

**Comment by davemachado** [comment]
@irfan-dahir thanks for the clarification - can you please put in alphabetical order?

**Comment by irfan-dahir** [comment]
Done.

**Comment by davemachado** [comment]
Thanks!

**Comment by irfan-dahir** [comment]
Thanks for adding!

**Pull request merged**
