### PR TITLE
Jikan API - Website + Description update

### PR DESCRIPTION
**Pull request by irfan-dahir**
Website update from `jikan.me` to `jikan.moe`. The former domain will expire on May 12th, 18.

Also a minor change to the description.

Thanks!

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @irfan-dahir , can you please remove the `.net` from the Description? It may introduce a regression with our CI builds in the future since it appears to be a link.

**Comment by irfan-dahir** [comment]
Sure thing, done.

**Comment by davemachado** [comment]
Thanks!

**Comment by irfan-dahir** [comment]
Thank you!

**Pull request merged**
