### PR TITLE
Add PiXHost API to readme

### PR DESCRIPTION
**Pull request by pfftdammitchris**
PiXhost like imgur is a image hosting service and is free to all users. Some people who have slightly more graphical content that gets rejected at imgur switch to PiXhost because it has more lenient rules. It also has an API that is not known.

From their website:

"Welcome to the PiXhost API!
You can use this API to upload images, covers or galleries.
The following image formats are supported: image/gif, image/png, image/jpeg. Maximum image size is 10 MB.
In case you have any ideas, questions or issues, feel free to contact us at: admin@pixhost.org.
Old API users: We recently enforced https, please update your scripts."

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @pfftdammitchris , thanks for the PR. Can you please remove the extra `|` at the end of `Description`? Thanks

**Comment by davemachado** [comment]
Oops, and all we need now is an ending `|` after the `Link` value :)

**Comment by davemachado** [comment]
@pfftdammitchris poke 😉

**Comment by jbrooksuk** [comment]
Waiting for tests to pass then this can be merged.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
