### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by woliveiras**
Add more social apis, related to: issue #58

### CODE REVIEW

**Comment by toddmotto** [comment]
Thanks for this, the Facebook one needs fixing though, then I'll merge! :)

**Comment by woliveiras** [comment]
Fixed @toddmotto :smile:. Sorry.

**Comment by toddmotto** [comment]
Hehe, no problem - thanks for the update :)

**Comment by woliveiras** [comment]
:smile:

**Pull request merged**
