### PR TITLE
Add Evil Insult Generator API

### PR DESCRIPTION
**Pull request by EvilInsultGenerator**
I added our [Evil Insult Generator](https://evilinsult.com/) API. Please do not hesitate to ask any questions you may have.
For example, I was unsure about the right category and the link as I do not have a "landing page" for the API like [https://api.chucknorris.io/](https://api.chucknorris.io/).
Thanks!  😘

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @EvilInsultGenerator , thanks for the PR. Is there any documentation for this service? I looked around the site and could not find anything that described endpoints, rate limits, pricing tiers (if any), etc.

**Comment by davemachado** [comment]
Bump

**Comment by EvilInsultGenerator** [comment]
Sorry, for the delay.  😅 

The API is accessible via https://evilinsult.com/generate_insult.php.
It supports plain text, XML and JSON. 
The usage of the API is completely free. 

Example for an English insult with JSON output: https://evilinsult.com/generate_insult.php?lang=en&type=json

Status Page: https://stats.uptimerobot.com/NLnZ8sVro

**Comment by EvilInsultGenerator** [comment]
I added an [Evil Insult Generator API doc](https://evilinsult.com/api/) 👌🏽

**Pull request closed without merging**
