### PR TITLE
Added FavQs Quote API

### PR DESCRIPTION
**Pull request by piedcipher**
Another Quotes API. It provides various options to get quotes and perform operations like Update, Delete, Up-vote, Favourite, Hide, Tag on a quote. Random Quote doesn't require API key. You can request quotes from a specific category as well.

**EDIT** - My Previous PR resulted into Travis Build failed, that's why I'm submitting a new PR.

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by karllhughes** [comment]
@piedcipher you should be able to push new commits to get the build to pass. No need to keep opening new PRs ;-)

**Comment by karllhughes** [comment]
And BTW, I think the problem is the casing. `apikey` should be `apiKey`.

**Comment by piedcipher** [comment]
I fixed that type. :)

**Comment by mikestreety** [comment]
Good work team!

**Pull request merged**
