### PR TITLE
Adding Federal Register

### PR DESCRIPTION
**Pull request by ryanwmarsh**
The Federal Register is the daily journal of the US Government. It catalogs rulings, proposed rules, items for public inspection, and notices. 

For an example of what the API provides try this link:
https://www.federalregister.gov/api/v1/documents/2017-10853.json

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

### CODE REVIEW

**Comment by jbrooksuk** [comment]
You need to change the README.md and not the JSON :)

**Comment by davemachado** [comment]
@jbrooksuk 52ee255a41dfee3c4e15e03a0a8463fb73043bb2 should help with this moving forward ✅

**Comment by jbrooksuk** [comment]
👍🏻

**Comment by davemachado** [comment]
@ryanwmarsh poke ;)

**Comment by davemachado** [comment]
@ryanwmarsh poking one last time, since this is going on about a month old. 🕐

**Comment by davemachado** [comment]
I added this service in 53e196cef0b1247718f8adc3a4416176f740f642, so closing this PR.

**Pull request closed without merging**
