### PR TITLE
Add Dog API

### PR DESCRIPTION
**Pull request by ChrisGuzman**

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @ChrisGuzman , thanks for the PR! Can you please remove API from the title? Everything on this list is an API, so no need to specify.

**Comment by ChrisGuzman** [comment]
@davemachado done!

**Comment by johnnagro** [comment]
this is rad :surfing_man:

**Comment by davemachado** [comment]
@ChrisGuzman Thanks!

**Pull request merged**
