### PR TITLE
Add contributing guide

### PR DESCRIPTION
**Pull request by davemachado**
As discussed in issue #140 , this contributing guide will hopefully assist contributors in easily opening PRs, and SHOULD help clear up the auth inconsistency moving forward (if people read the directions :) )

### CODE REVIEW

**Comment by mikestreety** [comment]
I've just finally changed the column to auth! Would appreciate a sanity check from a couple of others before we do the merge

**Comment by jbrooksuk** [comment]
I've made a few changes. Let me know.

**Comment by mikestreety** [comment]
I got an email every time 😉 .

Your changes look good. I'm happy if you are! Will wait for the final nod from @davemachado as it was his original PR!

**Comment by jbrooksuk** [comment]
> I got an email every time 😉 .

Web editor 😆

**Comment by davemachado** [comment]
looking good, @mikestreety- Thanks for the updates @jbrooksuk !

**Pull request merged**
