### PR TITLE
Added Countries

### PR DESCRIPTION
**Pull request by andyjballgit**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] Your additions are ordered alphabetically
- [ ] Your submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column should be padded with one space on either side
- [ ] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by andyjballgit** [comment]
Added Countries API

**Comment by gitoct** [comment]
It looks like a section requires a minimum of 3 entries to pass the checks, could you please add two additional country APIs?

**Comment by jbrooksuk** [comment]
I think it could live under **Geocoding**?

**Comment by andyjballgit** [comment]
Yep geocoding works for me

From my phone ,excuse brevity and typos

________________________________

**Comment by davemachado** [comment]
Bump

**Pull request closed without merging**
