### PR TITLE
Jekyll site with search feature

### PR DESCRIPTION
**Pull request by kuhnrl30**
Simple site with the ability to search.  I leaned heavily on http://2factorauth.org to integrate the search feature.  There's a pre-commit webhook to take the latest json file from /json and copy it to the /docs/_data directory.  That should keep the site in sync with the json generated off the README file. Once merged in, you'd have to change the settings to build from the /docs folder.

You can demo at http://ryankuhn.net/public-apis 

Before merging into the master branch, update the repo link in /docs/_includes/header.html.  Also, would recommend adding a link to the site on the README file.

### CODE REVIEW

**Comment by mikestreety** [comment]
I'm sure we could do something about the masses of bootstrap files? I assume it makes the repo quite chunky. The CSS is minimal styling anyway, and the JS could be reduced to this:

https://codepen.io/mikestreety/pen/QgxQbd

In fact, as I write this, I'm sure it can be done without jQuery! I'll have a think :)

**Comment by jbrooksuk** [comment]
I vote for Vue.js 😉

**Comment by mikestreety** [comment]
I would _always_ vote for Vue.

**Comment by mikestreety** [comment]
Something like this @jbrooksuk?

**Comment by davemachado** [comment]
I like those classy checkmarks @mikestreety 

I like the simpleness of not having a ton of overbearing information (what type of auth, for example).

In the original argument....I mean discussion...people were concerned about having an overly complicated website which really only adds a filtering mechanism. Playing for the other side of the discussion, what can moving this project to a website offer that the github project can't?

**Comment by mikestreety** [comment]
Ha! The missing auth type was a complete accident - I'd forgotten it was a string!

**Comment by jbrooksuk** [comment]
Perfect @mikestreety. That does everything we need.

**Comment by davemachado** [comment]
@kuhnrl30 took a quick glance through the diffs, couple of things to note:

- No need to add `Gemfile.lock` to VC
- No need to add `_site` to VC (generated during `jekyll build`, which we will hook into Travis)

**Comment by davemachado** [comment]
@kuhnrl30 There are also some files that we won't need (`.gitignore`, duplicate `json`, etc), but that can be cleaned up when this moves further along.

**Comment by davemachado** [comment]
I think a good path forward would be to clean this up a bit (rolling with that nice Vue setup, remove unneeded files from VC, ...) and merge the changes into a new branch on the project. From there, followup tweaks can be made to get the site candidate ready for use in this project, not the fork (update the build process, pull latest HEAD json, ...).

**Comment by mikestreety** [comment]
To clairfy, would users update the JSON, or does this convert the readme into JSON?

**Comment by mikestreety** [comment]
Great :)

**Comment by davemachado** [comment]
So we are just a day shy of having this open for a month. I'd like to start making some more progress on the process of making a site for this project, so I'm going to start moving forward with a basic site to offer up along this same vein (using @mikestreety beautiful Vue suggestion, of course 🥇 ) 

Therefore, I move to close this PR - all in favor?

**Comment by jbrooksuk** [comment]
🙌 close in favour of yours.

**Pull request closed without merging**
