### PR TITLE
Added BungieNetPlatform API

### PR DESCRIPTION
**Pull request by MrDecipher**
Added link to Bungie API for developing Destiny The Game apps.

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @MrDecipher , thanks for the PR. It looks like the service Destiny provides is a companion mobile app to go along with the game - not so much an endpoint/ development service. Can you please confirm or point to documentation on the service?

**Comment by MrDecipher** [comment]
Hi @davemachado ,
It is a fully fledged API for Destiny related application development but requires users to register on the site to access the API. If the user is not registered the link will redirect the user to download the companion application. I realized this after I signed out of my account and went to the API page. I will change the link to the forum post below since it details how to access the API and doesn't requires users to register to view.

https://www.bungie.net/en/Clan/Post/39966/85087279/0/0

Documentation links:
https://www.bungie.net/platform/destiny/help/

**Comment by davemachado** [comment]
Looks good, thanks!

**Comment by MrDecipher** [comment]
👍

**Pull request merged**
