### PR TITLE
Added OvApi.nl

### PR DESCRIPTION
**Pull request by Nickforall**
OvAPI is a collection of a lot of Dutch public transportation APIs in the GTFS format.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This contains two additions?

**Comment by Nickforall** [comment]
No. I edited the description of the ns.nl API. NS is the Dutch national railways, and "Transport for The Netherlands" did not seem appropriate to me, for an api that only provides info for trains,

**Comment by jbrooksuk** [comment]
Could you make those changed in individual commits please, rebasing them onto the current `master`.

**Comment by toddmotto** [comment]
Yeah need to fix merge conflicts before we can merge, thanks!

**Comment by toddmotto** [comment]
Closing

**Pull request closed without merging**
