### PR TITLE
Added FHIR to "Health" API section

### PR DESCRIPTION
**Pull request by toddanglin**
Added link to API for publicly available test data conforming to the Fast Healthcare Interoperability Resources (FHIR) spec published by University Health Network. 

- [X] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [X] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [X] Your additions are ordered alphabetically.
- [X] Your submission has a useful description.
- [X] Each table column should be padded with one space on either side.
- [X] You have searched the repository for any relevant issues or PRs.
- [X] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by karllhughes** [comment]
Does this API actually provide usable data or is it some kind of test bed? I'm not familiar with the medical records industry so it's hard for me to tell by reading the description.

**Comment by toddanglin** [comment]
It's usable "dummy data" that conforms to the spec. So data types include things like:

- Patient
- Medication
- Practitioner

You can browse the various data types and result sets here: http://fhirtest.uhn.ca/home?encoding=null&pretty=true

It is not a technical test bed. It provides data that could be used to create demos that wanted to include healthcare data. Does that help?

**Comment by davemachado** [comment]
Hi @toddanglin , thanks for the PR! Can you please move this to the `Test Data` section?

**Comment by toddanglin** [comment]
Sure...makes sense. Moved it.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
