### PR TITLE
Added more crypto currency exchanges including nexchange and poloniex

### PR DESCRIPTION
**Pull request by shakyink**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON 
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @shakyink , please fix your formatting on line 165. Thank you.

**Comment by shakyink** [comment]
Hi @davemachado, the address that I am using for the `LINK` for the poloniex exchange is working as expected and I'm following the entries as an example. Is there anything I need to do the API documentation address for it validate correctly?

Here is the output I see in the travis build
```sh
$ python --version
Python 3.6.3
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
install
2.53s$ pip install -r build/requirements.txt
Collecting flake8>=3.5.0 (from -r build/requirements.txt (line 1))
  Downloading flake8-3.5.0-py2.py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 5.4MB/s 
Collecting httplib2==0.9.2 (from -r build/requirements.txt (line 2))
  Downloading httplib2-0.9.2.zip (210kB)
    100% |████████████████████████████████| 215kB 5.5MB/s 
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8>=3.5.0->-r build/requirements.txt (line 1))
  Downloading pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 10.8MB/s 
Collecting pyflakes<1.7.0,>=1.5.0 (from flake8>=3.5.0->-r build/requirements.txt (line 1))
  Downloading pyflakes-1.6.0-py2.py3-none-any.whl (227kB)
    100% |██████████████████���█████████████| 235kB 7.6MB/s 
Collecting mccabe<0.7.0,>=0.6.0 (from flake8>=3.5.0->-r build/requirements.txt (line 1))
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Building wheels for collected packages: httplib2
  Running setup.py bdist_wheel for httplib2 ... -done
  Stored in directory: /home/travis/.cache/pip/wheels/c7/67/60/e0be8ccfc1e08f8ff1f50d99ea5378e204580ea77b0169fb55
Successfully built httplib2
Installing collected packages: pycodestyle, pyflakes, mccabe, flake8, httplib2
Successfully installed flake8-3.5.0 httplib2-0.9.2 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.6.0
before_script.1
0.58s$ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
0
before_script.2
0.48s$ flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
0
before_script.3
0.00s$ cd build
0.05s$ ./main.sh
running format validation...
(L165) link syntax should be "[Go!](LINK)"
format validation failed!
```

**Comment by davemachado** [comment]
Looks like you have one too many `No`'s or `Yes`'s on line 165.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
