### PR TITLE
Added Utilities section & the first service for it (JSON 2 JSONP)

### PR DESCRIPTION
**Pull request by fevangelou**
Sometimes a service may not provide its data directly in JSONP for use with client-side JS. This high-availability service (already serving more than 7m requests monthly) can assist in converting data output in JSON to JSONP.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Would this not be better suited under https://github.com/toddmotto/public-apis#development?

**Comment by fevangelou** [comment]
Sure, it was just a recommendation :)

**Comment by jbrooksuk** [comment]
Np!

I think we're better keeping the categories simpler :) I'll merge once this is updated.

**Comment by fevangelou** [comment]
Done.

**Comment by jbrooksuk** [comment]
Oh, I should've updated the merge commit message, but hey ho. Thanks!

**Comment by fevangelou** [comment]
Thank you :)

**Pull request merged**
