### PR TITLE
Add PostcodeData.nl

### PR DESCRIPTION
**Pull request by PeterKassenaar**

### CODE REVIEW

**Comment by wesbos** [comment]
Can you squash into one commit?

**Comment by jbrooksuk** [comment]
@wesbos if there are any which have conflicts and need squashing, assign to me and I can take care of them one by one :)

**Comment by mikestreety** [comment]
This got merged, but squashed the commits

https://github.com/toddmotto/public-apis/commit/fb63b642d714d813c164219fc8ef5a819370cb8b

**Comment by PeterKassenaar** [comment]
Thanks guys. You fixed it before I had the chance to investigate.

**Pull request closed without merging**
