### PR TITLE
Added url link for Singapore Onemap

### PR DESCRIPTION
**Pull request by crizzs**
Sharing Singapore's Mapping Services.

### CODE REVIEW

**Comment by mikestreety** [comment]
Hi @crizzs,

Thanks for this link - a couple of updates if you don't mind?

1) Would you mind putting in alphabetical order?
2) Would you mind removing the rogue extra line that's appeared please?

**Comment by crizzs** [comment]
Hi Mike,

Certainly, we will update it when I am at home.

Regards,
Kai Cong

**Comment by mikestreety** [comment]
@crizzs Nudge 😄

**Comment by crizzs** [comment]
So sorry!!! It has slipped my mind.
I had just changed the readme file :D

**Comment by mikestreety** [comment]
All merged. Thanks

**Pull request merged**
