### PR TITLE
Add language detection API - detectlanguage.com

### PR DESCRIPTION
**Pull request by laurynas**

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @laurynas , thanks for the PR. Can you please remove `API` from the title of this service? Thanks!

**Comment by laurynas** [comment]
Hi @davemachado, updated service title.

**Comment by davemachado** [comment]
great, now it just needs to be in alphabetical order 😉

**Comment by laurynas** [comment]
updated :)

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
