### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by infiniteloopltd**
Added Car Registration API

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [ ] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by infiniteloopltd** [comment]
Added our Car Registration API

**Comment by mikestreety** [comment]
Hi @infiniteloopltd - thanks for the PR. Would you mind adding this in the correct place alphabetically, please? Thanks!

**Comment by mikestreety** [comment]
It also appears this is a paid-for service. This API list is for free APIs or ones with a free tier. Can you confirm please?

**Comment by infiniteloopltd** [comment]
Hi,

  I've changed the ordering, it's now alphabetically ordered.

  There is a free tier, for a limited number of searches after a new account is opened.

Thanks!

Fiach

**Comment by davemachado** [comment]
Hi @infiniteloopltd , it appears that the free tier is a stock 10 queries for a new account. Can you confirm if the stock is ever reset or does an account only ever have 10 free hits?

**Comment by davemachado** [comment]
@infiniteloopltd poke :)

**Comment by davemachado** [comment]
Did some more digging, and it appears those 10 credits are never reset, so closing this as an invalid paid service.

**Pull request closed without merging**
