### PR TITLE
Added Climacell public API

### PR DESCRIPTION
**Pull request by roughley**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [X] Your additions are ordered alphabetically
- [X] Your submission has a useful description
- [X] The description does not end with punctuation
- [X] Each table column should be padded with one space on either side
- [X] You have searched the repository for any relevant issues or pull requests
- [X] Any category you are creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by davemachado** [comment]
Hello @roughley thanks for the PR! Please address all CI issues before this will be reviewed.

**Comment by davemachado** [comment]
Hi @roughley , I restarted the build and HTTPS passes now. However, I cannot find any description of pricing on the website, only references to a "free trial" of some kind. Can you please comment with a link to pricing documentation? Thanks.

**Comment by roughley** [comment]
The link I provided (https://developer.climacell.co) provides information on the 2 options available.  They are (1) free (for 1000 calls/day), and (2) enterprise, the enterprise version has a free 30 day trial and per-customer pricing.

Do you think this messaging is too confusing?

**Comment by davemachado** [comment]
Looks good, thanks!

**Comment by roughley** [comment]
Thanks!

**Pull request merged**
