### PR TITLE
Removed dead Coinbin link

### PR DESCRIPTION
**Pull request by mildrenben**

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @mildrenben , thanks for the PR! I know a lot of cryptocurrency servers have been taking a huge server hit recently thanks to Bitcoin's 🚀 ride, so let's give Coinbin some time to recover before cutting them off. I will recheck this in a couple days.

**Comment by mildrenben** [comment]
Good call. I didn't even think of the possibility the servers were just getting thrashed.

Side note - would be great to have a tool that ran to check server responses from all these APIs to weed out dead services. Might get a little annoying with the authorised ones, but for the no auth ones it could be worthwhile, maybe something that runs on a pre-push hook?

**Comment by davemachado** [comment]
something like this? 😉 
https://github.com/toddmotto/public-apis/blob/master/build/validate_links.rb

**Comment by mildrenben** [comment]
😅  must have missed that!

**Comment by davemachado** [comment]
After some Google-fu, it appears that Coinbin has gone under (for now...). Moving ahead with removing.

**Pull request merged**
