### PR TITLE
JSON is auto-generated, don't touch

### PR DESCRIPTION
**Pull request by jbrooksuk**
This may help.

### CODE REVIEW

**Comment by mikestreety** [comment]
Can we also add a note or a checkbox to the "Pull request template"

_Please only update the readme - the JSON will get auto generated one your pull request has been merged_

**Comment by jbrooksuk** [comment]
We have!

https://github.com/toddmotto/public-apis/blame/master/.github/PULL_REQUEST_TEMPLATE.md#L6

**Comment by mikestreety** [comment]
Oh 🤔

**Comment by jbrooksuk** [comment]
Perhaps it needs to be more obvious.

**Pull request merged**
