### PR TITLE
Added BetterDoctor API

### PR DESCRIPTION
**Pull request by albertpak**
BetterDoctor API entry

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @albertpak , please fix the issues outlined in the failed build - thanks!

**Comment by davemachado** [comment]
Also, could you please remove the duplicate title in the Description?

**Comment by albertpak** [comment]
@davemachado got it :) errors fixed

**Comment by davemachado** [comment]
Thanks for fixing the build errors - could you also please update the description to something a little bit easier to chew, maybe something like, `Detailed information about local doctors` ?

**Comment by albertpak** [comment]
@davemachado description has been updated - let me know if its good to go or needs something else

**Comment by davemachado** [comment]
Looks great, thanks! 🎉

**Pull request merged**
