### PR TITLE
added marijuana strain api to Readme

### PR DESCRIPTION
**Pull request by THEAverageSpeedBurrito**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by THEAverageSpeedBurrito** [comment]
Some of the checks failed although I don't think this is related to my addition.

**Comment by davemachado** [comment]
Hi @THEAverageSpeedBurrito , thanks for the PR. Can you please remove `API` from the title and `2000+` from the description? Thanks

**Comment by THEAverageSpeedBurrito** [comment]
Updated the submission to comply with your request. Thanks for the feedback

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
