### PR TITLE
Add a 'Jokes' API

### PR DESCRIPTION
**Pull request by 15Dkatz**
This change adds a 'Jokes' API to the "Games and Comics" section.

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by xnekv03** [comment]
Hello, it does support https

**Comment by TerryMooreII** [comment]
Just FYI before this gets merged, after looking at the api code it appears that there is a grand total of 17 jokes available in this api.  `https://github.com/15Dkatz/official_joke_api/blob/master/jokes/index.json` 
Not sure if this is the type of thing that we would want in this list.

**Comment by 15Dkatz** [comment]
:haircut_man: @xnekv03

**Comment by xnekv03** [comment]
? Wut?

**Comment by mikestreety** [comment]
I have enjoyed all 17 of those jokes. MERGE IT!

**Pull request merged**
