### PR TITLE
Add LoremPicsum API

### PR DESCRIPTION
**Pull request by AdrienRedon**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [x] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [x] Your additions are ordered alphabetically.
- [x] Your submission has a useful description.
- [x] Each table column should be padded with one space on either side.
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by TorzuoliH** [comment]
Hi!

Is it really an API?

It seems to be images hosted on LoremPicsum domain but not there's no endpoints for getting data from this domain.

**Comment by AdrienRedon** [comment]
In order to get a picture, the endpoint is like the following: 
```lorempicsum.com/{nameOfCartoon}/{width}/{height}/{pictureNumber}```

For instance: 
```lorempicsum.com/futurama/800/600/2```
will return the second picture of futurama with a width of 800 and a height of 600

The specificity is that you can request wichever size you need the picture to be.

**Comment by TorzuoliH** [comment]
@AdrienRedon Ok I see.

To be specified: `pictureNumber` is a number between 1 & 9.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
