### PR TITLE
Add whitepages pro APIs

### PR DESCRIPTION
**Pull request by sakulich**
add phone and address validation
add phone reputation to detect spammy numbers. 
add fraud prevention api section

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @sakulich , thanks for the PR. It appears that none of these APIs are free from WhitePages. This list is a collection of free-to-use services, all of which offer at least some form of a free tier. Can you confirm?

**Comment by sakulich** [comment]
Hi @davemachado i think there is a way to get up to 2000 free request for something like phone validation, but I doubt there is a free plan.

**Comment by davemachado** [comment]
Thanks for the clarification @sakulich . If you can share something that shows the 2000 free requests for some service, we can definitely take a look at adding that service to the list. However, since this list's purpose is for free-to-use tools for developers to use, we can't add any services that are explicitly paid solutions. In any case, thanks for the contribution and I encourage you to open more in the future!

**Comment by sakulich** [comment]
Aboslutely, @davemachado, here is the link to sign up for a free trial, not if that is enough. 
https://pro.whitepages.com/developer/lp/start-api-trial/?plan_param=reverse_phone&utm_campaign=pro-api-trial-reversephone

**Comment by davemachado** [comment]
Good news! I did a bit of digging and according to this [page](https://pro.whitepages.com/developer/documentation/api-overview/), developers can get a free API key with a rate limit of 4 queries per second, so it looks like Whitepages will work after all. @sakulich , can you please create one entry for the collective WhitePages APIs, instead of creating separate entries per endpoint? The schema for this project keeps similar services offered by the same company in one listing. Also, if you'd like to create a `Fraud Protection` section, please make sure to add it in alphabetical order. Thanks!

**Comment by sakulich** [comment]
Great! thank you @davemachado, updated my PR.

**Comment by davemachado** [comment]
Thanks!

**Comment by sakulich** [comment]
thanks @davemachado !

**Pull request merged**
