### PR TITLE
Add Open Science Framework API

### PR DESCRIPTION
**Pull request by caseyrollins**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [X] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [X] Your additions are ordered alphabetically.
- [X] Your submission has a useful description.
- [X] Each table column should be padded with one space on either side.
- [X] You have searched the repository for any relevant issues or PRs.
- [X] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @caseyrollins , thanks for the PR. Looks like this API does use OAuth for authentication. Can you please update accordingly? Thanks!

**Comment by caseyrollins** [comment]
@davemachado, indeed, we support OAuth and apikey/token auth as well! 

I can change `No` to `OAuth, apiKey`, however, authentication is not _required_ to interact with the OSF API and the contributing guidelines stated: 
> Does this API require authentication?

Let me know which is intended. Thanks!

**Comment by caseyrollins** [comment]
Correct! The API provides a wealth of information without authentication (i.e. access to all of our publicly posted projects, data, and research materials). Auth is only required for managing projects within your account.

**Comment by davemachado** [comment]
Thanks for the contribution!

**Pull request merged**
