### PR TITLE
Added the CryptoStandardizer API

### PR DESCRIPTION
**Pull request by ymslavov**

### CODE REVIEW

**Comment by davemachado** [comment]
hi @ymslavov , thanks for the PR. Please resolve any build failures.

**Comment by ymslavov** [comment]
@davemachado build fail addressed. I guess you're squashing the commits before merging, but let me know if you want me to rebase that fix commit into the main one. Thanks!

**Comment by davemachado** [comment]
@ymslavov looks like you committed your IDE files. Please remove.

**Comment by ymslavov** [comment]
@davemachado fixed.

**Comment by davemachado** [comment]
Thanks!

**Pull request merged**
