### PR TITLE
Added czech national bank exchange rates and Imgur correction

### PR DESCRIPTION
**Pull request by xnekv03**
Czech national bank exchange rates
Corrected Imgur URL

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md).
- [ ] Your changes are made in the [README](../README.md) file, not the auto-generated JSON. 
- [ ] Your additions are ordered alphabetically.
- [ ] Your submission has a useful description.
- [ ] Each table column should be padded with one space on either side.
- [ ] You have searched the repository for any relevant issues or PRs.
- [ ] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @xnekv03 , thanks for the PR! Could you please reorder into alphabetical order? Thanks!

**Comment by davemachado** [comment]
Now you just need to resolve the merge conflicts ;)

**Comment by xnekv03** [comment]
Sorry for my dumb question, but how do I do that? This is my very first PR ever.

Thank you

**Comment by davemachado** [comment]
[Here's a doc ](https://help.github.com/articles/resolving-a-merge-conflict-on-github/)on resolving conflicts 😄

**Comment by xnekv03** [comment]
Thank you,
anything else I need to do?

**Comment by davemachado** [comment]
Looks good, thanks!

**Comment by xnekv03** [comment]
No, thanks to YOU!

**Pull request merged**
