### PR TITLE
APIs.guru: Wikipedia for Web APIs

### PR DESCRIPTION
**Pull request by IvanGoncharov**
My catalog has [OpenAPI/Swagger](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) descriptions for 200+ APIs and 6000+ endpoints. People build interesting startup/projects on top of it:
https://github.com/APIs-guru/api-models#existing-integrations

P.S. It's really funny to add API for catalog of API descriptions into this API catalog :smile: 
we-need-to-go-deeper_inception

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
We will release better API docs in a few days.
Afterward, I will update URL and also rebase this PR.

**Comment by IvanGoncharov** [comment]
@toddmotto I updated URL and rebased.
It ready to be merged.
Can you please review it?

**Comment by IvanGoncharov** [comment]
Yet another rebase 😄

**Comment by toddmotto** [comment]
Thanks for this, all merged :)

**Pull request merged**
