### PR TITLE
Add Link Verification through CI

### PR DESCRIPTION
**Pull request by davemachado**
Speaking to Issue #11 , I think it is important to keep a running check on all existing links to make sure at a bare minimum that there is still some website to link to, rather than it just being a dead link taking space up on the page. Currently it seems the only way we can tell if a service has died is if someone tries to use it and the link is dead or the user is connected to the service in some way - either way, it doesn't look too good from a maintaining standpoint. It seems like this tool will do the job for us, and it opens the door for any other schweet CI-checking fun in the future!

### CODE REVIEW

**Comment by davemachado** [comment]
Oh, and we'll obviously being needing @toddmotto to give the green light and turn Travis on for this project. :)

**Comment by davemachado** [comment]
FYI, this was the result from testing the CI script on my fork - lots of outdated links and newly HTTPS-ified services!
awesome-bot

**Comment by jbrooksuk** [comment]
:+

**Comment by mikestreety** [comment]
Awesome work!

**Comment by davemachado** [comment]
pinging @toddmotto so this doesn't end up dying off ;)

**Comment by toddmotto** [comment]
Ah sorry guys for the delay. Travis is on!

**Comment by toddmotto** [comment]
Hmmm Travis doesn't seem to be triggering a build yet :/

**Comment by hsorellana** [comment]
does travis depend on any way on amazon?? i'm asking because some the amazon services are down :(

**Comment by toddmotto** [comment]
Yeah, I was just came back here to say "Ignore me, S3 is down and so is Travis". Thought I was losing my mind 😅

**Comment by toddmotto** [comment]
Thanks to the status gator (doesn't sound as cool with my English accent): https://statusgator.com/services/travis-ci

**Comment by davemachado** [comment]
Just got the first passing build! :)

**Comment by mikestreety** [comment]
Does this need updating now? https://github.com/toddmotto/public-apis/blob/master/CONTRIBUTING.md

**Comment by davemachado** [comment]
moving this over to PR #294

**Pull request merged**
