### PR TITLE
Add 2 new api(s) (sebisauce, phobia) and catagories (Fun, Information)

### PR DESCRIPTION
**Pull request by Annihilator708**
Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items

### CODE REVIEW

**Comment by davemachado** [comment]
Hi @Annihilator708 , thanks for the PR. Looks like your fork is wildly out of date. Please rebase accordingly.

**Comment by Annihilator708** [comment]
@davemachado If i am not mistaking a did update to the current state,

**Comment by davemachado** [comment]
screen shot 2018-03-29 at 3 17 02 pm

You tell me 😉

**Comment by davemachado** [comment]
Bump

**Pull request closed without merging**
